services:
    ldes-time-fragmenter:
        ports:
            - 8888:3000
            - 9229:9229
        environment:
            NODE_ENV: "development"
            DATA_FOLDER: "/data"
        volumes:
            - .:/app/
            - /app/data
            - /app/datasets
