services:
    ldes-time-fragmenter:
        build: .
        environment:
            DATA_FOLDER: "/data"
        volumes:
            - ./data/:/data/
        networks:
            - ldes-network
networks:
    ldes-network:
        name: ldes-network
